import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";





const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-nunito",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${nunito.variable}`} >
      <body
       className= {nunito.className}
      >
        {children}
      </body>
    </html>
  );
}
