import type { Metadata } from "next";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";

import ReactQueryProvider from "@/provider/reactQueryProvider";
import { Toaster } from "react-hot-toast";
import ToastProvider from "@/provider/toastProvider";
import ReduxProvider from "@/provider/ReduxProvider";

export const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-nunito",
});

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body className={nunito.className}>
        <ReduxProvider>
          <ReactQueryProvider>
            <GoogleOAuthProvider
              clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
            >
              <ToastProvider>{children}</ToastProvider>
            </GoogleOAuthProvider>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
